Add `JSONPathDetailTypeMapper`
awslabs/eventbridge-kafka-connector pull request #464
Opened 2024-12-29 21:21 UTC by embano1

Description
-----------

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

#272 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-30 14:22 UTC, embano1 commented
@maschnetwork @agebhar1 don't be too harsh with me :D

2025-01-01 12:05 UTC, agebhar1 requested changes
LGTM w/ some remarks.

2025-01-01 12:05 UTC, agebhar1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +          JsonPath.using(jsonPathConfiguration).parse(jsonNode.toString()).read(jsonPath);
It's a bit redundant to parse the bytes to JSON, serialize and parse again. You can omit the Jackson parsing by using the `parse` method from `JsonPath`:
```java
      var extractedValue =
          JsonPath.using(jsonPathConfiguration).parse(new String(jsonBytes)).read(jsonPath);
```
and add a `catch` block:
```
    } catch (IllegalArgumentException e) {
      // TODO: discuss throw or error
      log.error(
          "Parsed JSON node is null for record '{}', using topic '{}' as fallback", record, topic);
      return topic;
    } catch (Exception e) {
```

2025-01-01 16:20 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +        // TODO: discuss throw or error
@agebhar1 any thoughts on the TODOs left here?

2025-01-02 18:19 UTC, maschnetwork requested changes
Great contribution! First review done - please see comments for open discussions.

2025-01-02 18:19 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    if (record == null) {
Can you think of any use case where this would be null? Afaik Connect would only deliver valid _SinkRecords that have been read from Kafka and include the kafkaOffset of the record in the Kafka topic-partition in addition to the standard fields (From the [docs](https://kafka.apache.org/20/javadoc/org/apache/kafka/connect/sink/SinkRecord.html#kafkaOffset))._

In addition, at that stage we have gone through several chains and stages before and should ideally filter null values there without making it the mapper responsibility to check. Wdyt?

2025-01-02 18:19 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      var jsonNode = objectMapper.readTree(jsonBytes);
Is jsonNode only needed for verification purposes?

2025-01-02 18:19 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      if (((String) extractedValue).trim().isEmpty()) {
Do we need that level of detail for the different steps or can we catch most of them at once and return a single warning/error and return the fallback?

2025-01-02 18:55 UTC, agebhar1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      var jsonNode = objectMapper.readTree(jsonBytes);
@embano1 did forget to delete it, it's verified by
```
    JsonPath.using(jsonPathConfiguration).parse(new String(jsonBytes))
```
some lines below

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
> +  public static final String AWS_DETAIL_TYPES_MAPPER_JSON_PATH_MAPPER_FIELDREF =
I've gone back and forth on this: since it's an out of the box implementation provided by the connector that users can opt-in I thought it would be good to have it being part of the connector config (incl. validation and overall tests). 

Can you elaborate on:

> What about leveraging `aws.eventbridge.detail.types` as a generic field for mapper configuration 

I'm already using this path to overload/extend. If you mean to just use that field directly, the issue is that it would not allow for multiple configuration values if needed.

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +              // com.jayway.jsonpath.ReadContext#read throws an exception if JSON path could
Good eye ,)

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    this.jsonConverter = new JsonConverter();
Sorry, not following :) (Java noob alert)

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    if (record == null) {
Yup, this is really just to make some linters/reviews happy - should never happen. But I don't think it hurts to have it in the code base explicitly.

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +        // TODO: discuss throw or error
@maschnetwork same question for you.

2025-01-02 20:27 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      if (((String) extractedValue).trim().isEmpty()) {
User experience: IMHO required to make it easier for users to understand the cause.

2025-01-02 20:34 UTC, embano1 commented on README.md
> +| `aws.eventbridge.detail.types.mapper.class`       | No       |
Sorry, where?

2025-01-02 20:34 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      var jsonNode = objectMapper.readTree(jsonBytes);
Uff, yes removed!

2025-01-02 20:38 UTC, embano1 commented on README.md
> +The `JsonPathDetailTypeMapper` is a built-in implementation that allows you to extract the EventBridge `detail-type`
Slightly changed wording, but left "extract" here and there. Should be better now. Good suggestion!

2025-01-02 20:50 UTC, maschnetwork commented on README.md
> +| `aws.eventbridge.detail.types.mapper.class`       | No       |
Topic to `dtail-type` mapping

2025-01-02 21:00 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    this.jsonConverter = new JsonConverter();
Objectmapper is currently not used at all and can be removed. For JsonConverter we can do:

```java
private final JsonConverter jsonConverter = new JsonConverter();

public JsonPathDetailTypeMapper() {
  jsonConverter.configure(singletonMap(SCHEMAS_ENABLE_CONFIG, "false"), false);
}
```

2025-01-02 21:01 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +      if (((String) extractedValue).trim().isEmpty()) {
Ok - if we think about it from a libray perspectice I get it. Makes sense.

2025-01-02 21:11 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
> +  public static final String AWS_DETAIL_TYPES_MAPPER_JSON_PATH_MAPPER_FIELDREF =
> I've gone back and forth on this: since it's an out of the box implementation provided by the connector that users can opt-in I thought it would be good to have it being part of the connector config (incl. validation and overall tests).

 I see your point.

> I'm already using this path to overload/extend. If you mean to just use that field directly, the issue is that it would not allow for multiple configuration values if needed.

I can't follow this one. What I mean is to use `aws.eventbridge.detail.types` instead of a new field `aws.eventbridge.detail.types.jsonpathmapper.fieldref` to configure any kind of custom mapping behavior. But digging into the code it might be a little dangerous because we already have some logic for parsing here: 

https://github.com/awslabs/eventbridge-kafka-connector/blob/57438d5ee1cfd10a04a15b448d7fca88b6e4335f/src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java#L141-L149

My intention was to provide a general and more generic field that any custom mapper implementation could use to provide additional configuration. However, since we see this as an out of the box feature for the connector and we currently don't see a big demand in custom implementations we can also use the field as mentioned.

2025-01-02 21:35 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +        // TODO: discuss throw or error
What is the exact question here? Can you provide an example?

2025-01-03 13:45 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    this.jsonConverter = new JsonConverter();
Done

2025-01-03 13:47 UTC, embano1 commented on README.md
> +| `aws.eventbridge.detail.types.mapper.class`       | No       |
Fixed

2025-01-03 13:50 UTC, embano1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +        // TODO: discuss throw or error
There's currently two cases (TODOs) in the code where I wasn't sure whether I should throw or log an error and use the fallback (topic name). My proposal is to log an error but wanted to seek feedback here.

I think `if (jsonBytes == null)` case can be ignored in the discussion because it's just defensive code which should not happen in production.

the other case is when catching `IllegalArgumentException` (not sure which cases would trigger it, this was recommended by @agebhar1 )

```java
catch (IllegalArgumentException e) {
      // TODO: discuss throw or error
      log.error(
          "Could not extract JSON value for JSON path '{}' and record '{}', using topic '{}' as fallback",
          jsonPath,
          record,
          topic);
      return topic;
```

2025-01-03 13:53 UTC, embano1 commented
@maschnetwork all feedback address, remaining discussion: https://github.com/awslabs/eventbridge-kafka-connector/pull/464#discussion_r1901804063

2025-01-03 14:14 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +          JsonPath.using(jsonPathConfiguration).parse(jsonNode.toString()).read(jsonPath);
@embano1 @agebhar1 IllegalArgumentException is thrown when jsonBytes would result in an empty string:

https://github.com/json-path/JsonPath/blob/45333e0a310af70ad48d34d306da30af1e8e6314/json-path/src/main/java/com/jayway/jsonpath/internal/ParseContextImpl.java#L36 

What about checking this in our non null check before and then we can remove the catch clause and keept it simple with the null case together.

2025-01-03 14:34 UTC, maschnetwork commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +        // TODO: discuss throw or error
See comment below on the catch clause - we can potentially remove this and should also replace the catch all and rethrow at the bottom with log.error and returning the fallback.

In general I would propose to not throw in this method at all - either the JsonPath works or we have a fallback. Maybe even a `.warn` instead of `.error` for the fallback cases that we are covering explicitly.

Maybe in the rare circumstance that a topic is null and the fallback does not work we can keep the throw.

2025-01-03 15:28 UTC, agebhar1 commented on src/main/java/software/amazon/event/kafkaconnector/mapping/JsonPathDetailTypeMapper.java
> +    if (record == null) {
As far as I can remember it should be optimized/removed by the JVM HotSpot during runtime.

2025-01-03 16:07 UTC, embano1 commented
@maschnetwork feedback addressed, commits squashed

2025-01-03 16:14 UTC, maschnetwork approved these changes
lgtm thanks @embano1

2025-01-03 16:17 UTC, merged